spring.application.name=project

# URL a tu base de datos
spring.datasource.url=jdbc:postgresql://localhost:5432/loquehay
spring.datasource.username=postgres
spring.datasource.password=0712


# Driver
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

# Dialecto recomendado para Postgres
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# JWT
jwt.secret=MiClaveSuperSecretaQueDebeSerMuyLargaYGuardadaEnVault
jwt.expiration-ms=3600000
# Mail (configura con tus credenciales SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=tu-email@gmail.com
spring.mail.password=tu-app-password
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# URL del frontend para los links de reset
app.frontend-url=http://localhost:5173
